export const MIN_AMOUNT_OF_WITHDRAWING = 1;
export const MAX_AMOUNT_OF_PURCHASE = 10000;
export const USER_REFERENCE_PERCENTAGE = 10;
export const COMISSION_PERCENTAGE = 2;
export const GAMES_AMOUNT = 10;
export const START_BOT_BALANCE = 1000;
export const BOTS_AMOUNT = 100;
export const FAKE_GAME_MIN_BET = 10;
export const FAKE_GAME_MAX_BET = 50;
export const GAME_CHECK_INTERVAL = 2000;
export const GAME_EXPIRE_DELLAY = 5000;
export const GAME_UPDATE_FAKES_INTERVAL = 1800000;

export default {
  MIN_AMOUNT_OF_WITHDRAWING,
  MAX_AMOUNT_OF_PURCHASE,
  USER_REFERENCE_PERCENTAGE,
  COMISSION_PERCENTAGE,
  GAMES_AMOUNT,
  GAME_EXPIRE_DELLAY,
  START_BOT_BALANCE,
  BOTS_AMOUNT,
  FAKE_GAME_MIN_BET,
  FAKE_GAME_MAX_BET,
  GAME_CHECK_INTERVAL,
};
