export const MAX_AMOUNT_OF_PURCHASE = 10000;
export const MIN_AMOUNT_OF_WITHDRAWING = 1;
export const USER_REFERENCE_PERCENTAGE = 5;

export default {
  MIN_AMOUNT_OF_WITHDRAWING,
  MAX_AMOUNT_OF_PURCHASE,
  USER_REFERENCE_PERCENTAGE,
};
