// export const GAME_MIN_ALIVE_GAMES_AMOUNT = 1;
export const GAME_USER_TIMEOUT = 15000;
export const GAME_SPIN_DELAY = 8000;
export const GAME_CHECK_DELLAY = 1000;
export const GAME_MIN_CHANCE_TO_WIN = 5;
export const GAME_MAX_CHANCE_TO_WIN = 95;
export const GAME_MAX_ATTEMPTS = 10;
export const GAME_MIN_PRIZE = 1;
export const GAME_MAX_PRIZE = 20000;
export const GAME_UPDATE_FAKES_INTERVAL = 1800000;
export const GAME_CHECK_INTERVAL = 2000;
export const MIN_WITHDRAWS_TO_SHOW = 20;
export const START_USER_BALANCE = 50;
export const START_BOT_BALANCE = GAME_MAX_PRIZE / 2;
// export const START_BOT_BALANCE = START_USER_BALANCE;
export const REQUIRED_PAID_TO_WITHDRAW = 1;
export const GAMES_AMOUNT = 200;
export const MAX_ATTEMPTS = 10;
export const MIN_CHANCE_TO_WIN = 5;
export const MAX_CHANCE_TO_WIN = 95;
export const MIN_AMOUNT_OF_PURCHASE = 100;
export const MAX_AMOUNT_OF_PURCHASE = 10000;
export const COINS_RATE = 0.01;
export const LOW_LEVEL_GAME_PRIZE_TRESHOLD = 50;
export const TABLES_AMOUNT = 20;
export const TABLES_STEP = 1000;
export const GAMES_IN_TABLE = 40;
export const MIN_AMOUNT_OF_WITHDRAWING = 1;

export default {
  REQUIRED_PAID_TO_WITHDRAW,
  MIN_AMOUNT_OF_WITHDRAWING,
  GAMES_AMOUNT,
  MAX_ATTEMPTS,
  MIN_CHANCE_TO_WIN,
  MAX_CHANCE_TO_WIN,
  MIN_AMOUNT_OF_PURCHASE,
  MAX_AMOUNT_OF_PURCHASE,
  GAME_SPIN_DELAY,
  START_USER_BALANCE,
  COINS_RATE,
  GAME_MIN_PRIZE,
  GAME_MAX_PRIZE,
};
