module.exports = {
  up: (queryInterface) => {
    return queryInterface.bulkInsert('Tariffs', [
      {
        name: 'BEGINNER',
        minDuration: 1,
        maxDuration: 3,
        minReplenishment: 5,
        minCredit: 5,
        maxCredit: 25,
        percentage: 8,
        minReliability: 60,
        maxReliability: 69,
        insurance: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'BASE',
        minDuration: 1,
        maxDuration: 7,
        minReplenishment: 25,
        minCredit: 5,
        maxCredit: 50,
        percentage: 5,
        minReliability: 70,
        maxReliability: 79,
        insurance: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ADVANCED',
        minDuration: 1,
        maxDuration: 14,
        minReplenishment: 50,
        minCredit: 5,
        maxCredit: 100,
        percentage: 3,
        minReliability: 80,
        maxReliability: 89,
        insurance: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EXPERT',
        minDuration: 1,
        maxDuration: 30,
        minReplenishment: 100,
        minCredit: 5,
        maxCredit: 500,
        percentage: 2,
        minReliability: 90,
        maxReliability: 99,
        insurance: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },
  down: (queryInterface) => {
    return queryInterface.bulkDelete('Tariffs', null);
  },
};
